import { shiftDate, shiftMonth, type DemoData } from "./model.ts";

export function createDemo(today: string): DemoData {
  const month = today.slice(0, 7);
  const day = (number: number) => `${month}-${String(number).padStart(2, "0")}`;
  const monthEnd = shiftDate(`${shiftMonth(month, 1)}-01`, -1);
  return {
    accounts: [
      {
        id: "bank",
        owner: "jiwoo",
        kind: "bank",
        name: "생활 통장",
        opening: "1000000",
      },
      {
        id: "trip",
        owner: "jiwoo",
        kind: "bank",
        name: "여행 통장",
        opening: "300000",
      },
      {
        id: "cash",
        owner: "jiwoo",
        kind: "cash",
        name: "지갑",
        opening: "50000",
      },
      {
        id: "credit",
        owner: "jiwoo",
        kind: "credit",
        name: "일상 신용카드",
        opening: "0",
      },
      {
        id: "debit",
        owner: "jiwoo",
        kind: "debit",
        name: "생활 체크카드",
        opening: "0",
        linkedId: "bank",
      },
      {
        id: "other-bank",
        owner: "haneul",
        kind: "bank",
        name: "하늘 통장",
        opening: "200000",
      },
    ],
    records: [
      {
        id: "dinner",
        owner: "jiwoo",
        kind: "event",
        title: "함께 저녁식사",
        date: today,
        endDate: today,
        allDay: false,
        startTime: "19:00",
        endTime: "20:30",
        visibility: "shared",
        note: "동네 파스타집에서 만나요.",
      },
      {
        id: "dinner-cost",
        owner: "jiwoo",
        kind: "expense",
        title: "저녁식사",
        date: today,
        amount: "60000",
        accountId: "credit",
        category: "식비",
        visibility: "shared",
        note: "함께 먹은 저녁",
      },
      {
        id: "gift",
        owner: "jiwoo",
        kind: "expense",
        title: "개인 선물",
        date: today,
        amount: "30000",
        accountId: "debit",
        category: "쇼핑",
        visibility: "private",
        note: "나만 보는 메모",
      },
      {
        id: "salary",
        owner: "jiwoo",
        kind: "income",
        title: "급여",
        date: day(25),
        amount: "2500000",
        accountId: "bank",
        category: "급여",
        visibility: "private",
        note: "",
      },
      {
        id: "transfer",
        owner: "jiwoo",
        kind: "transfer",
        title: "여행비 옮기기",
        date: today,
        amount: "20000",
        fromId: "bank",
        toId: "trip",
        category: "",
        visibility: "private",
        note: "",
      },
      {
        id: "travel",
        owner: "jiwoo",
        kind: "event",
        title: "가을 여행",
        date: monthEnd,
        endDate: shiftDate(monthEnd, 2),
        allDay: true,
        startTime: "",
        endTime: "",
        visibility: "shared",
        note: "2박 3일, 함께 쉬어 가요.",
      },
      {
        id: "cafe",
        owner: "haneul",
        kind: "expense",
        title: "카페",
        date: today,
        amount: "12000",
        accountId: "other-bank",
        category: "식비",
        visibility: "shared",
        note: "여행 이야기",
      },
      {
        id: "snack",
        owner: "haneul",
        kind: "expense",
        title: "개인 간식",
        date: today,
        amount: "5000",
        accountId: "other-bank",
        category: "식비",
        visibility: "private",
        note: "",
      },
      {
        id: "walk",
        owner: "jiwoo",
        kind: "event",
        title: "저녁 산책",
        date: day(12),
        endDate: day(12),
        allDay: false,
        startTime: "18:00",
        endTime: "19:00",
        visibility: "shared",
        note: "공원에서 만나요.",
      },
      {
        id: "family",
        owner: "haneul",
        kind: "event",
        title: "가족과 점심",
        date: day(6),
        endDate: day(6),
        allDay: false,
        startTime: "12:00",
        endTime: "14:00",
        visibility: "shared",
        note: "",
      },
      {
        id: "movie",
        owner: "jiwoo",
        kind: "event",
        title: "영화 보는 날",
        date: day(19),
        endDate: day(19),
        allDay: false,
        startTime: "17:00",
        endTime: "19:00",
        visibility: "shared",
        note: "",
      },
    ],
  };
}
